platform: linux

image_resource:
  type: docker-image
  source:
    repository: jamesdbloom/docker-java8-maven
    tag: 'latest'

inputs:
  - name: git-repo

run:
  path: mvn
  args: ["-f", "git-repo/pom.xml", "package"]