resources:
  - name: git-repo
    type: git
    source:
      uri: {{gist-url}}
      branch: master
  - name: time
    type: time
    source:
      interval: 60s
  - name: docker-output
    type: docker-image


jobs:
  - name: maven-clean
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
      - get: time
    - task: maven-clean
      privileged: true
      file: git-repo/clean.yml

  - name: maven-test
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
        passed: [maven-clean]
    - task: maven-test
      privileged: true
      file: git-repo/test.yml
    - put: docker-output
      params:
        pull_repository: ubuntu

  - name: maven-package
    plan:
    - aggregate:
      - get: git-repo
        passed: [maven-test]
      - get: docker-output
        passed: [maven-test]
    - task: maven-package
      privileged: true
      file: git-repo/package.yml